test_average (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... ERROR
test_to_degrees (__main__.TestExercice) ... ERROR
test_to_farenheit (__main__.TestExercice) ... ERROR
test_to_radians (__main__.TestExercice) ... ok

======================================================================
ERROR: test_to_celsius (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 68, in test_to_celsius
    output = [exercice.to_celsius(v) for v in values]
  File "test_exercice.py", line 68, in <listcomp>
    output = [exercice.to_celsius(v) for v in values]
  File "/home/runner/work/c01_ch3_exercices-cardinal60/c01_ch3_exercices-cardinal60/exercice.py", line 25, in to_celsius
    return to_celsius(temperature)
  File "/home/runner/work/c01_ch3_exercices-cardinal60/c01_ch3_exercices-cardinal60/exercice.py", line 25, in to_celsius
    return to_celsius(temperature)
  File "/home/runner/work/c01_ch3_exercices-cardinal60/c01_ch3_exercices-cardinal60/exercice.py", line 25, in to_celsius
    return to_celsius(temperature)
  [Previous line repeated 972 more times]
RecursionError: maximum recursion depth exceeded

======================================================================
ERROR: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 56, in test_to_degrees
    output = [exercice.to_degrees(v) for v in values]
  File "test_exercice.py", line 56, in <listcomp>
    output = [exercice.to_degrees(v) for v in values]
  File "/home/runner/work/c01_ch3_exercices-cardinal60/c01_ch3_exercices-cardinal60/exercice.py", line 20, in to_degrees
    to_degrees (deg + minutes * 60 + seconds * 3600)
  File "/home/runner/work/c01_ch3_exercices-cardinal60/c01_ch3_exercices-cardinal60/exercice.py", line 20, in to_degrees
    to_degrees (deg + minutes * 60 + seconds * 3600)
  File "/home/runner/work/c01_ch3_exercices-cardinal60/c01_ch3_exercices-cardinal60/exercice.py", line 20, in to_degrees
    to_degrees (deg + minutes * 60 + seconds * 3600)
  [Previous line repeated 972 more times]
RecursionError: maximum recursion depth exceeded

======================================================================
ERROR: test_to_farenheit (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 80, in test_to_farenheit
    output = [exercice.to_farenheit(v) for v in values]
  File "test_exercice.py", line 80, in <listcomp>
    output = [exercice.to_farenheit(v) for v in values]
  File "/home/runner/work/c01_ch3_exercices-cardinal60/c01_ch3_exercices-cardinal60/exercice.py", line 29, in to_farenheit
    return to_farenheit(temperature)
  File "/home/runner/work/c01_ch3_exercices-cardinal60/c01_ch3_exercices-cardinal60/exercice.py", line 29, in to_farenheit
    return to_farenheit(temperature)
  File "/home/runner/work/c01_ch3_exercices-cardinal60/c01_ch3_exercices-cardinal60/exercice.py", line 29, in to_farenheit
    return to_farenheit(temperature)
  [Previous line repeated 972 more times]
RecursionError: maximum recursion depth exceeded

----------------------------------------------------------------------
Ran 5 tests in 0.011s

FAILED (errors=3)
